---
abstract: 'a module providing a unified way to deal with'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-Phonology
no_index:
  directory:
    - t
    - inc
requires:
  B::Deparse: 0.63
  Parse::RecDescent: < 1.967
  XML::Simple: 2.08
version: 0.352
